### ISSUE TITLE
Rendering example compilation error

### ISSUE THREAD

**Issue by FerdinK** [albin-johansson/centurion#105]
Hi ! 

I took an example from the doxygen documentation, and tried to compile it, however, it gives me errors:

The code:
```
#define CENTURION_CONFIGURATION_MACRO
#include <centurion.hpp>

int main()
{
    cen::library centurion;
    auto [window, renderer] = cen::make_window_and_renderer();

    window.show();
    renderer.clear_with(cen::colors::light_coral);

    renderer.set_color(cen::colors::red);
    renderer.fill_circle(cen::point(150.0f, 150.0f), 75);

    renderer.set_color(cen::colors::cyan);
    renderer.draw_circle(cen::point(350, 275), 50);

    renderer.set_color(cen::colors::khaki);
    renderer.draw_rect(cen::rect(550, 50, 140, 60));

    renderer.set_color(cen::colors::forest_green);
    renderer.draw_line(cen::point(240, 340), cen::point(360, 460));

    renderer.present();

    using namespace cen::literals;
    cen::thread::sleep(2000_ms);

    window.hide();

    return 0;
}
```

The errors:
<details> D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105430): error C7568: argument list missing after assumed function template 'basic_texture'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(106485): note: see reference to class template instantiation 'cen::basic_renderer<T>' being compiled
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105430): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105430): error C2144: syntax error: 'unknown-type' should be preceded by ')'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105430): error C2144: syntax error: 'unknown-type' should be preceded by ';'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105430): error C2238: unexpected token(s) preceding ';'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105430): error C2988: unrecognizable template declaration/definition
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105430): error C2143: syntax error: missing ';' before '&'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105430): error C7538: 'basic_point<`template-type-parameter-1'>' is not a variable template
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105430): error C3735: template or generic redefined
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105430): warning C4228: nonstandard extension used: qualifiers after comma in declarator list are ignored
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105430): error C2059: syntax error: ')'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105432): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105460): error C7568: argument list missing after assumed function template 'basic_texture'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105460): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105460): error C2144: syntax error: 'unknown-type' should be preceded by ')'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105460): error C2144: syntax error: 'unknown-type' should be preceded by ';'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105460): error C2238: unexpected token(s) preceding ';'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105460): error C2086: 'unknown-type &cen::basic_renderer<T>::texture': redefinition
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105460): error C2988: unrecognizable template declaration/definition
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105460): error C2143: syntax error: missing ';' before '&'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105460): error C7538: 'basic_rect<`template-type-parameter-1'>' is not a variable template
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105460): error C3735: template or generic redefined
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105460): warning C4228: nonstandard extension used: qualifiers after comma in declarator list are ignored
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105460): error C2059: syntax error: ')'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105462): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105491): error C7568: argument list missing after assumed function template 'basic_texture'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105491): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105491): error C2144: syntax error: 'unknown-type' should be preceded by ')'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105491): error C2144: syntax error: 'unknown-type' should be preceded by ';'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105491): error C2238: unexpected token(s) preceding ';'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105491): error C2086: 'unknown-type &cen::basic_renderer<T>::texture': redefinition
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105492): error C2988: unrecognizable template declaration/definition
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105492): error C2143: syntax error: missing ';' before '&'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105492): warning C4228: nonstandard extension used: qualifiers after comma in declarator list are ignored
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105493): error C2059: syntax error: ')'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105494): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105523): error C7568: argument list missing after assumed function template 'basic_texture'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105523): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105523): error C2144: syntax error: 'unknown-type' should be preceded by ')'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105523): error C2144: syntax error: 'unknown-type' should be preceded by ';'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105523): error C2238: unexpected token(s) preceding ';'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105523): error C2086: 'unknown-type &cen::basic_renderer<T>::texture': redefinition
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105524): error C2988: unrecognizable template declaration/definition
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105524): error C2143: syntax error: missing ';' before '&'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105524): error C2086: 'unknown-type cen::basic_renderer<T>::irect': redefinition
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105524): warning C4228: nonstandard extension used: qualifiers after comma in declarator list are ignored
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105526): error C2059: syntax error: ')'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105527): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105569): error C7568: argument list missing after assumed function template 'basic_texture'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105569): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105569): error C2144: syntax error: 'unknown-type' should be preceded by ')'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105569): error C2144: syntax error: 'unknown-type' should be preceded by ';'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105569): error C2238: unexpected token(s) preceding ';'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105569): error C2086: 'unknown-type &cen::basic_renderer<T>::texture': redefinition
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105570): error C2988: unrecognizable template declaration/definition
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105570): error C2143: syntax error: missing ';' before '&'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105570): error C2086: 'unknown-type cen::basic_renderer<T>::irect': redefinition
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105570): warning C4228: nonstandard extension used: qualifiers after comma in declarator list are ignored
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105573): error C2059: syntax error: ')'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105574): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105622): error C7568: argument list missing after assumed function template 'basic_texture'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105622): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105622): error C2144: syntax error: 'unknown-type' should be preceded by ')'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105622): error C2144: syntax error: 'unknown-type' should be preceded by ';'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105622): error C2238: unexpected token(s) preceding ';'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105622): error C2086: 'unknown-type &cen::basic_renderer<T>::texture': redefinition
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105623): error C2988: unrecognizable template declaration/definition
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105623): error C2143: syntax error: missing ';' before '&'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105623): error C2086: 'unknown-type cen::basic_renderer<T>::irect': redefinition
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105623): warning C4228: nonstandard extension used: qualifiers after comma in declarator list are ignored
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105627): error C2059: syntax error: ')'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105628): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105677): error C7568: argument list missing after assumed function template 'basic_texture'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105677): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105677): error C2144: syntax error: 'unknown-type' should be preceded by ')'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105677): error C2144: syntax error: 'unknown-type' should be preceded by ';'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105677): error C2238: unexpected token(s) preceding ';'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105677): error C2086: 'unknown-type &cen::basic_renderer<T>::texture': redefinition
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105677): error C2988: unrecognizable template declaration/definition
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105677): error C2143: syntax error: missing ';' before '&'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105677): error C7538: 'basic_point<`template-type-parameter-1'>' is not a variable template
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105677): error C3735: template or generic redefined
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105677): warning C4228: nonstandard extension used: qualifiers after comma in declarator list are ignored
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105677): error C2059: syntax error: ')'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105679): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105699): error C7568: argument list missing after assumed function template 'basic_texture'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105699): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105699): error C2144: syntax error: 'unknown-type' should be preceded by ')'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105699): error C2144: syntax error: 'unknown-type' should be preceded by ';'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105699): error C2238: unexpected token(s) preceding ';'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105699): error C2086: 'unknown-type &cen::basic_renderer<T>::texture': redefinition
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105700): error C2988: unrecognizable template declaration/definition
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105700): error C2143: syntax error: missing ';' before '&'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105700): error C7538: 'basic_rect<`template-type-parameter-1'>' is not a variable template
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105700): error C3735: template or generic redefined
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105700): warning C4228: nonstandard extension used: qualifiers after comma in declarator list are ignored
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105700): error C2059: syntax error: ')'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105701): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105725): error C7568: argument list missing after assumed function template 'basic_texture'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105725): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105725): error C2144: syntax error: 'unknown-type' should be preceded by ')'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105725): error C2144: syntax error: 'unknown-type' should be preceded by ';'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105725): error C2238: unexpected token(s) preceding ';'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105725): error C2086: 'unknown-type &cen::basic_renderer<T>::texture': redefinition
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105726): error C2988: unrecognizable template declaration/definition
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105726): error C2143: syntax error: missing ';' before '&'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105726): error C2086: 'unknown-type cen::basic_renderer<T>::irect': redefinition
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105726): warning C4228: nonstandard extension used: qualifiers after comma in declarator list are ignored
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105727): error C2059: syntax error: ')'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105728): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105751): error C7568: argument list missing after assumed function template 'basic_texture'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105751): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105751): error C2144: syntax error: 'unknown-type' should be preceded by ')'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105751): error C2144: syntax error: 'unknown-type' should be preceded by ';'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105751): error C2238: unexpected token(s) preceding ';'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105751): error C2086: 'unknown-type &cen::basic_renderer<T>::texture': redefinition
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105752): error C2988: unrecognizable template declaration/definition
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105752): error C2143: syntax error: missing ';' before '&'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105752): error C2086: 'unknown-type cen::basic_renderer<T>::irect': redefinition
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105752): warning C4228: nonstandard extension used: qualifiers after comma in declarator list are ignored
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105754): error C2059: syntax error: ')'
D:\Programming\Projects\CPP\IdleGame-dependencies\includes\include\Centurion\centurion.hpp(105754): fatal error C1003: error count exceeds 100; stopping compilation
NMAKE : fatal error U1077: 'C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1429~1.300\bin\Hostx86\x86\cl.exe' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\bin\HostX86\x86\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\bin\HostX86\x86\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\bin\HostX86\x86\nmake.exe"' : return code '0x2'
Stop.
</details>

**Comment by FerdinK** [comment]
I should add that i'm using MSVC (from Visual Studio Community 2019) and CMake 3.20

**Comment by albin-johansson** [comment]
Hi!

The signature of your `main`-function is incorrect, it should be equivalent to `int(int, char**)` (see [this](https://albin-johansson.github.io/centurion/page-minimal-centurion-program.html) example). Changing the signature allows me to compile the code without any errors using MSVC 19.29.30040. 

I hope this fixes your issues, let me know otherwise! 😄

P.S. Note that `CENTURION_CONFIGURATION_MACRO` isn't an actual macro used by the library, it's a [placeholder](https://albin-johansson.github.io/centurion/configuration.html).

**Comment by FerdinK** [comment]
Oh, I used the placeholder my IDE generated without even looking at it, thanks for the reply anyway !
