### ISSUE TITLE
Creating custom blend modes

### ISSUE THREAD

**Issue by gxm11** [albin-johansson/centurion#106]
It seems that the library only supports blend modes like `blend/add/mod`. But I just want the subtract mode.

Would you like to support more blend modes or the `SDL_ComposeCustomBlendMode` to make any custom modes?

BTW, can I just directly use the function `SDL_ComposeCustomBlendMode` to create one blend mode and use it in this library?

**Comment by albin-johansson** [comment]
> Would you like to support more blend modes or the SDL_ComposeCustomBlendMode to make any custom modes?

The `blend_mode` enum only covers the blend modes provided by `SDL_BlendMode`. However, as you mentioned, you can use `SDL_ComposeCustomBlendMode()` to create custom blend modes that are perfectly fine to use (but they might not be supported by your graphics driver).

I see no reason why these APIs shouldn't be better covered in the library, so I'll look into wrapping `SDL_BlendFactor` and `SDL_ComposeCustomBlendMode()`.

I hope this clarifies things 😄

**Comment by gxm11** [comment]
Great! Much thanks!
