### ISSUE TITLE
Offscreen rendering

### ISSUE THREAD

**Issue by longnguyen2004** [albin-johansson/centurion#112]
How would I do offscreen rendering with this wrapper? After looking through the documentation, I don't see anything that is related to it. Can you add support for offscreen rendering?

**Comment by albin-johansson** [comment]
Hi!

Do you mean rendering to textures? If so, you can do this using the `set_target()`/`reset_target()` functions of `basic_renderer`. All textures created with the `texture_access::target` flag can be used as rendering targets.

**Comment by albin-johansson** [comment]
Was this what you were looking for? Or should I keep this issue open?

**Comment by longnguyen2004** [comment]
So what I need to do is call `make_window_and_renderer()`, change the target of the renderer, and discard the window (I plan to store the rendered output to a file). Is that correct?

**Comment by albin-johansson** [comment]
Basically yes. However, just to be clear, you only "discard" the window once (as in destroying it). You should not continuously create window instances.

> So what I need to do is call make_window_and_renderer()

Yes you need to create a window and renderer, but keep in mind that `make_window_and_renderer()` is just a convenience function for basically doing the following by yourself. There's no magic going on with that particular function.
```C++
cen::window window;
cen::renderer renderer{window};
```

> (I plan to store the rendered output to a file).

You can create a snapshot of the render target using `basic_renderer::capture()`, which returns a `surface` copy of the render target. Subsequently, you can save surfaces as for example PNG files using `basic_surface::save_as_png()`.

**Comment by longnguyen2004** [comment]
Alright, thanks for the help! This can be closed now.
