### ISSUE TITLE
Potential memory bug in Surface set/get pixel functions

### ISSUE THREAD

**Issue by bitset32** [albin-johansson/centurion#113]
G'day!

I noticed that the set/get pixel functions in `cen::basic_surface` assumes that `SDL_Surface::pixels` points to Uint32 data.

This may not be a safe assumption as the [documentation for SDL_MapRGBA](https://wiki.libsdl.org/SDL_MapRGBA) remarks:

> If the pixel format bpp (color depth) is less than 32-bpp then the unused upper bits of the return value can safely be ignored (e.g., with a 16-bpp format the return value can be assigned to a Uint16, and similarly a Uint8 for an 8-bpp format).

This seems to suggest that if your pixel format is smaller than 32-bit (say, RGB24), that you must memcpy only the first 3 bytes into `SDL_Surface::pixels`. This would also suggest that calculating the pixel index should involve the `SDL_Surface::format::bytesPerPixel` value.

I might be wrong about this, it came up as a concern while writing my own, similar library (using your library as a reference), but I haven't had a chance to test it myself.

**Comment by albin-johansson** [comment]
Hi!

Yeah, don't use the function unless you use a 32-bit format. I'll probably just remove this function in the next major version. 

Since you might be interested, there have been recent discussions to add official macros/functions to do this in SDL. See [this](https://github.com/libsdl-org/SDL/pull/4867) issue, which is currently included in the SDL 2.0.20 milestone.

**Comment by bitset32** [comment]
Removing the function is probably a fair call, accounting for different pixel sizes makes the function quite bulky and is a super inefficient way to manipulate pixels anyway. Thank you for sharing the resource, it would definitely be a useful feature to have in SDL.

**Comment by albin-johansson** [comment]
The related functions have been removed on the in-progress version 7.0.0 branch, so I'm closing this issue.
