### ISSUE TITLE
Texture copying?

### ISSUE THREAD

**Issue by Ayymoose** [albin-johansson/Centurion#123]
I've just briefly browsed `texture.hpp` and `renderer.hpp` because I was looking for how you implemented `operator=` for copying textures but there doesn't seem to be anything? Apologies if I've missed it but does Centurion support copying of surfaces/textures?

**Comment by albin-johansson** [comment]
Hi.

There is no obvious way to copy textures (there are no SDL functions for copying textures). However, you could create a target texture and render an existing texture to it. 

Surfaces, on the other hand, are copy constructible.
