### ISSUE TITLE
Load/Render Assets from Memory

### ISSUE THREAD

**Issue by wwderw** [albin-johansson/Centurion#124]
I tried searching through the obvious headers, is there way to load/render bundled assets from memory?  A LoadImageFromMemory(), LoadWaveFromMemory() etc available?  Something that I could take IMAGE_DATA, IMAGE_SIZE (and for audio/font files as well) and get that to load within the program?

**Comment by albin-johansson** [comment]
Hi!

Are you looking to load raw in-memory image data into textures, or do you simply want to load on-disk images (i.e. PNGs)? For the latter, there's `basic_renderer::make_texture`.

There's no great way to do it for in-memory assets using Centurion as of now. So there might be some room for improvement here for later versions. In SDL you might write something like to following, as you might be aware.

```C
SDL_RWops* ops = SDL_RWFromMem(ptrToMemory, sizeOfMemory);
SDL_Surface* surface = IMG_LoadPNG_RW(ops);
```

**Comment by wwderw** [comment]
It was for in memory.   I would use ld to link the asset files for embedding and from there load load them in.  Now this was using Raylib, as I'm trying to branch out, I was hoping something equivalent could be done outside of Raylib as well.
