### ISSUE TITLE
Support for deeper mathematical operations on `basic_vector3` and other `math` structs. 

### ISSUE THREAD

**Issue by zachross015** [albin-johansson/Centurion#127]
Is there any plan to support for binary operators such as `+` and `-` for the structs in `math.hpp`? I'm using these structs as part of an engine and there doesn't seem to be any implementation of these.

**Comment by zachross015** [comment]
As a note, I'd be willing to contribute to add these if it's not in the timeline anywhere. They'd be beneficial to the engine I'm working on anyways.

**Comment by albin-johansson** [comment]
Hi.

I don't see any particular reason why this couldn't be provided. Which particular structs do you think should have these operators overloaded?

**Comment by albin-johansson** [comment]
As a side note, `basic_vector3` was originally provided just for the old (now removed) haptic API. Whilst supporting `operator+` and `operator-` is easy, I would generally recommend libraries such as `glm` for use as a proper math library in an engine.

**Comment by zachross015** [comment]
Thanks for the quick reply!

Ahh I see, that makes sense. Thanks for the reccomendation on `glm`, I hadn't looked into that yet but will look further into this for math operations. 

I don't think it's too high of a priority, but when working with the `basic_vector3` it would be intuitive if it implemented the standard vector operations (such as the two you mentioned, possibly also multiplying by a scalar).
