### ISSUE TITLE
`file.close()` is broken

### ISSUE THREAD

**Issue by v1993** [albin-johansson/Centurion#133]
https://github.com/albin-johansson/centurion/commit/41f3ae7e3e91b311af9018e475709134b85ce28f#diff-6c7927e79826c492d2e7141c6019cca8c2664a5e1453945ecdb48d7207f2686aR70-R80

This is always broken since it leads to `SDL_RWclose` getting called at least twice - both on success and on error!

> https://wiki.libsdl.org/SDL2/SDL_RWclose:
> 
> Note that if this fails to flush the stream to disk, this function reports an error, but the [SDL_RWops](https://wiki.libsdl.org/SDL2/SDL_RWops) is still invalid once this function returns.

As such, call `release` to steal ownership of a pointer for this call instead like my PR did. There are no cases where this does not lead to file getting closed and thus the idea of resetting pointer only on success is incorrect.

**Comment by v1993** [comment]
I'd also suggest retaining the note that it allows you to ensure that file was successfully flushed to disk.

**Comment by albin-johansson** [comment]
Nice catch, this was fixed in 28e43f938a630bdda5e189ab59ef5a7a17bba5c7
