### ISSUE TITLE
Can't build on my system

### ISSUE THREAD

**Issue by GiuseppeCesarano** [albin-johansson/centurion#76]
Gcc throws an error that basically says it can't find std::strings in `include/exception.hpp`. Simply adding `#include <string>` fixed the problem.

**Comment by albin-johansson** [comment]
Hi again! 😊

As you mentioned, the `<string>` include is missing. On recent versions of MSVC and GCC I suspect that `std::string` leaks from `<string_view>`. What version of GCC are you using? If possible, try using GCC 9.3.0 or later.

Many thanks for letting me know and making Centurion a little bit better! The library will go headet-only in version 5.1.0, so you wont have to build it yourself.

**Comment by GiuseppeCesarano** [comment]
I'm using GCC 10.2.0. I can confirm that in MSVC the string header leaks from string_view, but GCC 10.2 doesn't include it in the string_view header, i don't know if 9.3 does.

Anyway the library looks really high quality and well documented too!

**Comment by albin-johansson** [comment]
That's good to know! This has now been fixed on the WIP 5.1.0 branch.

Thank you for your kind words, the library will be of even higher quality with a new mocked test suite in 5.1.0.
