### ISSUE TITLE
Link broken in readme.md

### ISSUE THREAD

**Issue by GiuseppeCesarano** [albin-johansson/centurion#77]
The first link in the documentation section is broken

**Comment by albin-johansson** [comment]
Hi! 

Sorry about that, thanks for letting me know! It's because the repo changed name from **C**enturion to **c**enturion. A simple fix is to change the C to be lowercase in the link. I'll make sure to fix this in v5.1 which I'm working on right now.

I hope that helps a little bit!

**Comment by albin-johansson** [comment]
This has been addressed in the work-in-progress branch for version 5.1.0, thanks for your help!
